### ISSUE TITLE
Stretch subviews to fill width in HFlow

### ISSUE THREAD

**Issue by collinhundley** [tevelee/SwiftUI-Flow#13]
Notice how in the following example, the subview widths are variable based on the available space. Each button has a minimum size (the text size) which is used to determine wrapping, then afterward the buttons are stretched proportionally to fill any remaining space.

How can we modify `HFlow` to achieve a similar effect?

<img width="607" alt="Screenshot 2024-06-20 at 9 28 29 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/239348b0-7645-4fa9-af6d-6325bd86a6bb">

**Comment by tevelee** [comment]
Hi @collinhundley, thank you for your excellent question! 

[I tried to implement](https://github.com/tevelee/SwiftUI-Flow/compare/feature/justification?expand=1) your request to create a justified layout. Unfortunately I could not come with a view that is fixed and flexible at the same time so far. Let me explain.

The implementation of the layout itself was straightforward (increase the proposed size of each row proportionally by the empty space), but the question is what views to put in the content. If I try an infinite width view (like `Color` or `.frame(maxWidth: .infinity)`) then it will take up all the available space and spread the width of a full row. If I try anything more constrained then they won't spread to fill up the available space. 
The solution if probably dead simple, but I couldn't figure it out yet. Let me know if you have any ideas.

**Comment by collinhundley** [comment]
@tevelee I ran into exactly the same problems that you did. I’ll keep experimenting and update here if I’m able to figure anything out. Thanks!

**Comment by tevelee** [comment]
![image](https://github.com/tevelee/SwiftUI-Flow/assets/443078/e7e91080-e80f-4d53-97df-5edb277f3d46)

I figured it out using `LayoutSubviews.dimensions(in:)`. According its [documentation](https://developer.apple.com/documentation/swiftui/layoutsubview/dimensions(in:)), proposing .zero should give you the minimum size. I'll create a new release later today with this updated functionality.

**Comment by tevelee** [comment]
I published a new release, 1.4.0. HFlow (and VFlow too) has a new justification argument. If set to .stretchItems then the layout will keep the spacings but propose a larger size for the rows (ideal for flexible buttons/boxes). Similarly, if set to .stretchSpacings then the items will remain the same size, but spaces will stretch (ideal for static text). 
Let me know if that is what you had in mind.

**Comment by collinhundley** [comment]
@tevelee good find! Unfortunately it looks like this update breaks a few things - even if we ignore the new justification argument. Try this:

```swift
#Preview {
    List {
        HFlow {
            Text("test 1")
                .background(.green)
            Text("test 2")
                .background(.green)
        }
    }
}
```

It looks normal:

<img width="442" alt="Screenshot 2024-06-24 at 1 34 06 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/a65bc50c-fb80-4c4d-83fe-fafc60223af7">

Now add some padding to the text, or make one a bordered button:

```swift
#Preview {
    List {
        HFlow {
            Text("test 1")
                .padding()
                .background(.green)
            Button("test 2") {}
                .buttonStyle(.bordered)
        }
    }
}
```
<img width="442" alt="Screenshot 2024-06-24 at 1 32 57 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/c547cae2-254e-451f-b786-9e5cf3da8b70">


`HFlow` seems to shrink the view down to just the width of the padding. Any ideas?

**Comment by collinhundley** [comment]
One other thing I noticed: I struggled to get `justification` to work at all, even mimicking your example code. But I finally realized that it currently only works when spanning multiple lines:

<img width="615" alt="Screenshot 2024-06-24 at 2 11 35 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/6e0d3498-6f5d-4acf-a8dd-575a752dc891">
<img width="615" alt="Screenshot 2024-06-24 at 2 11 54 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/554f7540-7f78-44ce-b316-99db3b185cf5">

**Comment by tevelee** [comment]
Apologies for the bug. I pushed out 1.4.1 hoping to get it fixed. 

Regarding the single line use-case, it's a valid point. So far the flow layout hasn't stretched to the full width of container it only reported the size it can fit in. I also had the assumption that justified layout only makes sense in the multiple line use-case. Now you're making me realize both assumptions are incorrect when you take into account the justified layout. Maybe the single-line use-case is just a plain old HStackLayout? Anyway, this feature requires changes in larger scope, I will think about it and get back to you.

**Comment by collinhundley** [comment]
Thanks for looking into this. The layout is somewhat working now, but I'm seeing a new issue now:

```swift
#Preview {
    List {
        HFlow(justification: .stretchItems) {
            ForEach(0..<9) { _ in
                Color.blue
                    .frame(height: 40)
                    .frame(minWidth: 40)
            }
        }
        .background(.green)
    }
}
```
<img width="446" alt="Screenshot 2024-06-24 at 5 26 19 PM" src="https://github.com/tevelee/SwiftUI-Flow/assets/9559558/6616df1a-3255-433d-a543-57df1e87fae4">

Notice how`HFlow` is shrinking to fit the width of the first row, rather than expanding the first row to fill the available space. This is probably related to your comment above; is there a simple change that can allow the container to fill the full width of the parent view?

**Comment by tevelee** [comment]
> is there a simple change that can allow the container to fill the full width of the parent view?

The simple change would be that sizeThatFits returns the proposed size. See my diff here: https://github.com/tevelee/SwiftUI-Flow/compare/feature/fill-container?expand=1

I'm not sure we want to do this for the general use-case (without justified) though. The built-in HStack, VStack, Grid layout also report the content size and not the container size. You can work around this by adding a `.frame(alignment: .leading)` around `HFlow`.

**Comment by collinhundley** [comment]
Your updated code in `feature/fill-container` is working great for me - with one small bug fix inside `sizeThatFits()`:

```sift
let size = lines
    .map(\.size)
    .reduce(.zero, breadth: max, depth: +)
    .adding(spacings, on: .vertical)
    .extending(to: proposedSize.replacingUnspecifiedDimensions().size(on: axis))
```

If `proposedSize` contains a `nil` dimension, your code falls back to `.infinity` which crashes the layout system. Replacing the unspecified dimensions makes it work correctly.

I agree that the expanding behavior should be restricted to justified layouts. It seems like only applying the `extending()` method in those cases should do the trick?

**Comment by tevelee** [comment]
I've made significant improvements in `1.5.0`. Feel free to play around with the `justification` options and the new `distributeItemsEvenly` parameter. 
Justified layout should fill the space offered by the container and should respect the minimum or maximum size constraint of each item in the layout.

**Comment by collinhundley** [comment]
Thanks @tevelee. It might be a good idea to update the inline docs with an explanation for `distributeItemsEvenly`.
