### ISSUE TITLE
Views render out of bounds instead of wrapping

### ISSUE THREAD

**Issue by Tunous** [tevelee/SwiftUI-Flow#17]
When I place a Text view with text that won't fit on the screen inside of HFlow layout it is rendered out of bounds. Instead I would expect for it to wrap and stay in bounds of the screen.

```swift
struct ContentView: View {
    var body: some View {
        HFlow {
            Text("Example long text that is longer than the width of the screen")
            Text("Other text")
            Text("text")
        }
    }
}
```

Result:

![Screenshot 2024-07-23 at 20 21 43](https://github.com/user-attachments/assets/d16f443d-fc9e-420d-b11f-0e0e37932978)

Expected result:

![Screenshot 2024-07-23 at 20 25 02](https://github.com/user-attachments/assets/fdb5edc8-e841-43b0-a8c5-2b781696315f)

**Comment by tevelee** [comment]
Thank you @Tunous for raising this issue. I haven't encountered this use-case before but it is a valid bug. Previously, HFlow and VFlow only measured the ideal size of each subview irrespective of the proposed size. Now it gets taken into account.

I published a new release (2.3.0) which aims to fix this issue. Let me know if you see any problems with it.
