### ISSUE TITLE
Alignment not working like expected

### ISSUE THREAD

**Issue by HaakonL** [tevelee/SwiftUI-Flow#20]
It seems to be an issue with horizontalAlignment, the items in the HFlow container stays centered, no matter what I choose for alignment.

```swift
ScrollView([.vertical], showsIndicators: false) {
    HFlow(horizontalAlignment: .leading, verticalAlignment: .top) {
        ForEach(["Summer"], id: \.self) { tag in
            HStack {
                Text("#").foregroundColor(.gray)
                Text(tag).foregroundColor(.black)
            }
            .padding(.vertical, 5)
            .padding(.horizontal, 15)
            .background(.yellow)
            .cornerRadius(3)
        }
    }
    .frame(maxWidth: .infinity)
}
.frame(maxWidth: .infinity)
```

Any suggestions regarding this? I need the tag to be aligned to the leading edge.

<img width="456" alt="Screenshot 2024-10-13 at 11 25 38" src="https://github.com/user-attachments/assets/8891afe0-740c-445e-b06d-8c9bedff77ce">

**Comment by tevelee** [comment]
Where you added `.frame(maxWidth: .infinity)`, you can also specify its alignment to be leading: `.frame(maxWidth: .infinity, alignment: .leading)`. It's the property of the frame modifier not the HFlow.
