### ISSUE TITLE
Package has min target iOS 15 but all public functions are available in iOS 16+

### ISSUE THREAD

**Issue by theoks** [tevelee/SwiftUI-Flow#6]
The package has a minimum target iOS 15 but all public functions are available in iOS 16+, which someone discovers after the package installation.

**Comment by tevelee** [comment]
Thanks to #1 it allows HFlow/VFlow to be conditionally included in projects that support older deployment targets. 
The Layout protocol was introduced in iOS 16. Theoretically, it’s possible to back-deploy some of the functionality with GeometryReaders but I did not look into it yet.

**Comment by JohnKuan** [comment]
I would greatly appreciate if this can be supported from iOS 15.

**Comment by tevelee** [comment]
Bumped to iOS 16, macOS 13, tvOS 16, watchOS 9 in release 2.0.0
